### ISSUE TITLE
GPL 3.0 License requires larger project to turn to GPL 3.0

### ISSUE THREAD

**Issue by ethan92429** [nhenneaux/jersey-httpclient-connector#8]
I am unable to use this connector in a larger project with the MIT license because we can't change license, and GPL 3.0 requires any project it is in to use the same license - which very often is impossible. I imagine there are many others who face this issue. Would it be possible to change this to an MIT license? Or some other less restrictive license? I can't wait to actually use it!

**Comment by nhenneaux** [comment]
Hi Ethan,

Unless I miss something, you can use it as a library in a MIT license
project but you cannot change it without distributing it?

Best regards,

Nicolas

**Comment by ethan92429** [comment]
![license summary](https://user-images.githubusercontent.com/8585379/95203266-8449ce00-07b0-11eb-83fa-bd943b530e7f.png)

Expressly states that the larger project must have the same license. This means that only projects with a GPL 3.0 license can possibly use this connector.

**Comment by nhenneaux** [comment]
I made a bit more search and actually it is debatable whether linking it
implies using GPL for the whole project or not.

I'll change the license to LPGL so that it is crystal clear that it can be
used as a library by others.

Thanks for letting me know,

Nicolas

**Comment by ethan92429** [comment]
Thank you Nicolas! I look forward to using the project with the updated license 😄

**Comment by nhenneaux** [comment]
Changed in https://github.com/nhenneaux/jersey-httpclient-connector/commit/fbee777c699f3bceddc8a582669e63ef32bc613d to LGPL
